### ISSUE TITLE
Connection Test error

### ISSUE THREAD

**Issue by raoulvanrossum** [josephaxisa/henry#6]
When 'henry pulse' is run, I get the following error message. To me it seems that the results list empty, although when I check the client id and client secret manually ( https://<your-looker-host-name>:19999/api-docs/index.html) , the connection works fine. I hope you have any suggestions. 

RUNNING (1/5) Testing Connections:   0% |                                                 |[00:00<?]
Traceback (most recent call last):
 File "/usr/local/bin/henry", line 11, in <module>
   load_entry_point('henry==0.0.1b2', 'console_scripts', 'henry')()
 File "/usr/local/lib/python3.7/site-packages/henry-0.0.1b2-py3.7.egg/henry/cli.py", line 273, in main
   result = pulse.run_all()
 File "/usr/local/lib/python3.7/site-packages/henry-0.0.1b2-py3.7.egg/henry/commands/pulse.py", line 28, in run_all
   result = self.check_connections()
 File "/usr/local/lib/python3.7/site-packages/henry-0.0.1b2-py3.7.egg/henry/commands/pulse.py", line 102, in check_connections
   for i in results:
TypeError: 'NoneType' object is not iterable

**Comment by maxgsoulcycle** [comment]
Having the same issue here, also getting unauthorized errors running anything. Config file seems correct and API3 credentials work in other stuff I've written and through the API explorer. Is there supposed to be a blank 'access_token' line in the config file?

**Comment by josephaxisa** [comment]
@maxgsoulcycle the config file does expect an access token per host right now. You're meant to set it as an empty string as shown below:

```
hosts:
  dev_looker:
    access_token: ''
    host: devhostname.looker.com
    id: AbCdEfGhIjKlMnOp
    secret: QrStUvWxYz1234567890
```
If this doesn't fix it, can you send me your logs from `~/.henry/log/` to jax@looker.com? I am more than happy to work with you to get to the bottom of this.

**Comment by emilieschario** [comment]
I'm also getting this error! Is there any progress here? I do have the config file configured correctly. I have a connection set up in my instance. I thought maybe it was looking for multiple connections, so we created a dummy connection. Same error. Would the logs help here @josephaxisa?

I have verified the API credentials using gazr, if that's helpful info.

**Comment by josephaxisa** [comment]
@emilieschario The reason you are seeing that error is because you have a .netrc file. It seems that the .netrc file credentials somehow override headers sent through the requests module. The solution for now would be to make sure the two files don't have the same credentials. I am currently collaborating with the creator of Gazer so that we both use the netrc file.

**Comment by emilieschario** [comment]
@josephaxisa Thanks so much for clarifying that! I have it working now! Thank you!
